### PR TITLE
Add cookie policy popup and footer link

### PR DESCRIPTION
**Pull request by deadlight**
## Done
Added cookie policy popup and footer link

## QA
 - ./run
 - Visit the site
 - See the cookie policy popup
 - Wait 10 seconds and see it disappear
 - See the cookie policy link in the footer

🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪

### CODE REVIEW

**Comment by anasereijo** [comment]
- can we put the first sentence in just one line?
- the close button doesn't look correctly positioned. please check [vanilla](https://docs.vanillaframework.io/en/patterns/notification)

screenshot-2018-11-14-at-10 02 46

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Comment by anthonydillon** [comment]
@deadlight the design comments should be reported upstream. Up to you if you do the changes locally with scratch scss.

**Comment by deadlight** [comment]
@anthonydillon did a quick local fix and reported upstream. Can you re-check the code.

**Comment by deadlight** [comment]
@anasereijo ready for review. I rebuilt the [demo]https://landscape-canonical-com-canonical-websites-pr-8.run.demo.haus/)

**Comment by anasereijo** [comment]
@deadlight looking good!

**Pull request merged**
